version: '3.8'
services:

  mongodb:
    image: bitnami/mongodb:4.4.2
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: bookdb
      MONGODB_USERNAME: bookuser
      MONGODB_PASSWORD: bookpass
      MONGODB_ROOT_PASSWORD: secret
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/bookdb --quiet
      start_period: 10s

  keycloak:
    image: jboss/keycloak:11.0.3
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
    healthcheck:
      test: "curl -f http://localhost:8080/auth || exit 1"
      start_period: 30s
