version: '3.5'
services:

  mongodb:
    image: mongo:3.6.3
    container_name: mongodb
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/bookdb --quiet
      start_period: 10s

  keycloak:
    image: jboss/keycloak:4.0.0.Final
    hostname: keycloak

    # 'my-keycloak' is set as container_name instead of 'keycloak' to avoid the conflict
    # that happens when using gradle-docker-compose plugin (started when integrationTest
    # runs). As far I understood, gradle-docker-compose writes new properties to the
    # containers it runs, for example, my-keycloak.tcp.8080. However, the
    # KeycloakSpringBootProperties.java is set to ignore unknown properties. So, if 'keycloak'
    # name is used, the plugin will create keycloak.tcp.8080 and an exception will be thrown.
    container_name: my-keycloak

    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8181:8080
    healthcheck:
      test: "curl -f http://localhost:8080/auth || exit 1"
      start_period: 10s
