management:
  security.enabled: false
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always

spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_ADDR:localhost}:${MONGODB_PORT:27017}/bookdb

keycloak:
  auth-server-url: http://${KEYCLOAK_ADDR:localhost}:${KEYCLOAK_PORT:8181}/auth
  realm: company-services
  resource: book-service
  ssl-required: external
  principal-attribute: preferred_username
  use-resource-role-mappings: true